import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {activityAnswerIsValid,buildActivity,nextActivityTarget} from "../lib/activity-flow";
import {buildFeedbackPayload,buildMetricPayload,METRIC_EVENTS} from "../lib/analytics";
import {EMPTY_DRAFT,type Activity,type Draft} from "../lib/domain";
import {canSelectForm,getCurrentForm} from "../lib/forms";
import {GOSUSLUGI_RECOVERY_URL,GOSUSLUGI_REGISTRATION_URL,GOSUSLUGI_SERVICE_URL} from "../lib/official";
import {buildPersonalKit,buildPersonalSubmissionGuide} from "../lib/personal-kit";
import {DRAFT_KEY,finishApplication,loadDraft,saveDraft,TTL_MS} from "../lib/storage";
import {analyzeTimeline,tenYearWindow} from "../lib/timeline";
import {validateDraft} from "../lib/validation";
import {beginCorrection,GOSUSLUGI_STEP,REVIEW_STEP,returnToReview} from "../lib/workflow";

const now=new Date("2026-09-22T12:00:00Z");
const activity=(from:string,to:string,current=false,id="a",kind:Activity["kind"]="work"):Activity=>({id,kind,from,to,current,organization:kind==="unemployed"?"НЕ РАБОТАЛ(А)":"TEST",position:kind==="work"?"TEST":"",address:"TEST"});
const store=()=>{const data=new Map<string,string>();return{data,getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>void data.set(k,v),removeItem:(k:string)=>void data.delete(k)}};
const base=(passportKind:"5y"|"10y"="10y")=>({...EMPTY_DRAFT,consent:true,passportKind,gosuslugiAccess:"yes",birthDate:"1990-01-01",gender:"female"}) as Draft;

test("wizard supports both 5 and 10 year CURRENT forms",()=>{assert.equal(getCurrentForm("5y").id,"passport-5y-186");assert.equal(getCurrentForm("10y").id,"passport-10y-996")});
test("FUTURE_DISABLED form cannot be selected",()=>assert.equal(canSelectForm("passport-future-83"),false));
test("10-year window is calculated without user date arithmetic",()=>assert.deepEqual(tenYearWindow(now),{start:"2016-09",end:"2026-09"}));
test("guided flow fills backwards and leaves no missing month",()=>{const items=[buildActivity({kind:"work",from:"2023-04",organization:"TEST",position:"TEST",address:"TEST"},"2026-09",now,"current")];assert.equal(nextActivityTarget(items,now),"2023-03");items.push(buildActivity({kind:"study",from:"2016-09",organization:"TEST",position:"",address:"TEST"},"2023-03",now,"past"));const result=analyzeTimeline(items,now);assert.equal(result.complete,true);assert.deepEqual(result.gaps,[]);assert.equal(result.percent,100)});
test("guided answers reject a date outside the uncovered gap",()=>assert.equal(activityAnswerIsValid({kind:"work",from:"2015-01",organization:"TEST",position:"TEST",address:"TEST"},"2026-09","2016-09"),false));
test("gap detector reports exact missing months",()=>assert.deepEqual(analyzeTimeline([activity("2016-09","2020-02"),activity("2020-07","",true,"b")],now).gaps,[{from:"2020-03",to:"2020-06"}]));
test("overlap detector reports exact intersection",()=>assert.deepEqual(analyzeTimeline([activity("2016-09","2022-01"),activity("2021-12","",true,"b")],now).overlaps,[{from:"2021-12",to:"2022-01"}]));
test("invalid reverse dates are detected",()=>assert.deepEqual(analyzeTimeline([activity("2024-06","2024-01")],now).invalid,["a"]));
test("draft restores all data and exact active step",()=>{const s=store(),draft={...EMPTY_DRAFT,consent:true,lastName:"ТЕСТ"};saveDraft(s,draft,8,1000);const loaded=loadDraft(s,1001);assert.equal(loaded.data?.lastName,"ТЕСТ");assert.equal(loaded.lastStep,8)});
test("legacy draft migrates the inserted Gosuslugi step",()=>{const s=store();s.setItem(DRAFT_KEY,JSON.stringify({data:EMPTY_DRAFT,lastStep:4,touchedAt:1000}));const loaded=loadDraft(s,1001);assert.equal(loaded.lastStep,5);assert.equal(loaded.data?.gosuslugiAccess,"")});
test("TTL 24h removes expired PII before returning it",()=>{const s=store();saveDraft(s,{...EMPTY_DRAFT,lastName:"ТЕСТ"},4,100);const loaded=loadDraft(s,100+TTL_MS);assert.equal(loaded.expired,true);assert.equal(loaded.data,null);assert.equal(s.getItem(DRAFT_KEY),null)});
test("finishApplication removes all local questionnaire content",()=>{const s=store();saveDraft(s,{...EMPTY_DRAFT,lastName:"ТЕСТ"},3,100);assert.equal(finishApplication(s),true);assert.equal(s.getItem(DRAFT_KEY),null)});
test("validation routes missing Gosuslugi answer to its early step",()=>assert.equal(validateDraft(EMPTY_DRAFT,now).find(x=>x.id==="gosuslugi-access")?.step,GOSUSLUGI_STEP));
test("validation issue links directly to relevant step",()=>{const issue=validateDraft(EMPTY_DRAFT,now).find(x=>x.id==="internal-series");assert.deepEqual(beginCorrection(issue!.step),{step:6,returnToReview:true})});
test("correction returns to review in one action",()=>assert.deepEqual(returnToReview(),{step:REVIEW_STEP,returnToReview:false}));
test("personal checklist hides irrelevant items",()=>{const plain=buildPersonalKit({...base(),changedName:"no",hasForeignPassport:"no"});assert.equal(plain.documents.some(x=>x.id==="foreign-passport"),false);const custom=buildPersonalKit({...base(),changedName:"yes",hasForeignPassport:"yes"});assert.equal(custom.documents.some(x=>x.id==="foreign-passport"),true);assert.equal(custom.documents.some(x=>x.id==="name-docs"),true)});
test("5-year personal filing guide requires two applications and three photos",()=>{const guide=buildPersonalSubmissionGuide(base("5y"));assert.match(guide.application,/двух экземплярах/);assert.match(guide.photos,/Три фотографии 35 × 45/);assert.ok(guide.places.some(x=>x.includes("МВД")))});
test("10-year personal filing guide uses one application and digital capture",()=>{const guide=buildPersonalSubmissionGuide(base("10y"));assert.match(guide.application,/одном экземпляре/);assert.match(guide.photos,/цифровое фотографирование/);assert.match(guide.note,/отпечатков/)});
test("no-account and recovery branches use only official HTTPS URLs",()=>{for(const value of[GOSUSLUGI_REGISTRATION_URL,GOSUSLUGI_RECOVERY_URL]){const url=new URL(value);assert.equal(url.protocol,"https:");assert.ok(url.hostname.endsWith("gosuslugi.ru"))}});
test("wizard exposes non-blocking no-account and recovery branches",()=>{const source=readFileSync(new URL("../app/page.tsx",import.meta.url),"utf8");assert.match(source,/Нет учётной записи/);assert.match(source,/Учётная запись есть, но не могу войти/);assert.match(source,/Подготовку можно продолжать/);assert.match(source,/Восстановите доступ на официальной странице/)});
test("analytics event allowlist includes the full anonymous funnel",()=>assert.deepEqual(METRIC_EVENTS,["visit","start","reached_review","kit_ready","gosuslugi_click"]));
test("analytics and feedback payloads contain no questionnaire fields",()=>{const events=METRIC_EVENTS.map(buildMetricPayload);const feedback=buildFeedbackPayload("up","  Понятно  ");assert.ok(events.every(x=>Object.keys(x).join()==="event"));assert.deepEqual(Object.keys(feedback),["rating","message"]);assert.equal(JSON.stringify({events,feedback}).includes("passport"),false)});
test("official Gosuslugi service URL is secure and contains no PII query",()=>{const url=new URL(GOSUSLUGI_SERVICE_URL);assert.equal(url.protocol,"https:");assert.equal(url.hostname,"www.gosuslugi.ru");assert.equal(url.pathname,"/600101/1/form");assert.equal(url.search,"")});
test("Gosuslugi opens in a new tab and PDF is labelled as a memo",()=>{const source=readFileSync(new URL("../app/result-screen.tsx",import.meta.url),"utf8");assert.match(source,/href={GOSUSLUGI_SERVICE_URL} target="_blank"/);assert.match(source,/Скачать подготовленные данные PDF/);assert.match(source,/не официальное заявление МВД/)});
