import test from "node:test";
import assert from "node:assert/strict";
import {activityAnswerIsValid,buildActivity,nextActivityTarget} from "../lib/activity-flow";
import {buildFeedbackPayload,buildMetricPayload} from "../lib/analytics";
import {EMPTY_DRAFT,type Activity,type Draft} from "../lib/domain";
import {canSelectForm,getCurrentForm} from "../lib/forms";
import {GOSUSLUGI_SERVICE_URL} from "../lib/official";
import {buildPersonalKit} from "../lib/personal-kit";
import {DRAFT_KEY,finishApplication,loadDraft,saveDraft,TTL_MS} from "../lib/storage";
import {analyzeTimeline,tenYearWindow} from "../lib/timeline";
import {validateDraft} from "../lib/validation";
import {beginCorrection,REVIEW_STEP,returnToReview} from "../lib/workflow";

const now=new Date("2026-09-22T12:00:00Z");
const activity=(from:string,to:string,current=false,id="a",kind:Activity["kind"]="work"):Activity=>({id,kind,from,to,current,organization:kind==="unemployed"?"НЕ РАБОТАЛ(А)":"TEST",position:kind==="work"?"TEST":"",address:"TEST"});
const store=()=>{const data=new Map<string,string>();return{data,getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>void data.set(k,v),removeItem:(k:string)=>void data.delete(k)}};

test("10-year window is calculated without user date arithmetic",()=>assert.deepEqual(tenYearWindow(now),{start:"2016-09",end:"2026-09"}));
test("guided flow fills backwards and leaves no missing month",()=>{
 let items:Activity[]=[];
 assert.equal(nextActivityTarget(items,now),"2026-09");
 items.push(buildActivity({kind:"work",from:"2023-04",organization:"TEST",position:"TEST",address:"TEST"},"2026-09",now,"current"));
 assert.equal(nextActivityTarget(items,now),"2023-03");
 items.push(buildActivity({kind:"study",from:"2016-09",organization:"TEST",position:"",address:"TEST"},"2023-03",now,"past"));
 const result=analyzeTimeline(items,now);
 assert.equal(result.complete,true);assert.deepEqual(result.gaps,[]);assert.equal(result.percent,100);
});
test("guided answers reject dates outside the uncovered gap",()=>assert.equal(activityAnswerIsValid({kind:"work",from:"2015-01",organization:"TEST",position:"TEST",address:"TEST"},"2026-09","2016-09"),false));
test("gap detector reports only exact missing months",()=>{const result=analyzeTimeline([activity("2016-09","2020-02"),activity("2020-07","",true,"b")],now);assert.deepEqual(result.gaps,[{from:"2020-03",to:"2020-06"}]);assert.ok(result.percent>0)});
test("overlap detector reports exact intersection",()=>assert.deepEqual(analyzeTimeline([activity("2016-09","2022-01"),activity("2021-12","",true,"b")],now).overlaps,[{from:"2021-12",to:"2022-01"}]));
test("draft restores all data and exact active step",()=>{const s=store(),draft={...EMPTY_DRAFT,consent:true,lastName:"ТЕСТ"};saveDraft(s,draft,7,1000);const loaded=loadDraft(s,1001);assert.equal(loaded.data?.lastName,"ТЕСТ");assert.equal(loaded.lastStep,7)});
test("TTL 24h removes expired PII before returning it",()=>{const s=store();saveDraft(s,{...EMPTY_DRAFT,lastName:"ТЕСТ"},4,100);const loaded=loadDraft(s,100+TTL_MS);assert.equal(loaded.expired,true);assert.equal(loaded.data,null);assert.equal(s.getItem(DRAFT_KEY),null)});
test("finishApplication removes all local questionnaire content",()=>{const s=store();saveDraft(s,{...EMPTY_DRAFT,lastName:"ТЕСТ"},3,100);assert.equal(finishApplication(s),true);assert.equal(s.getItem(DRAFT_KEY),null)});
test("validation issue links directly to relevant step",()=>{const issue=validateDraft(EMPTY_DRAFT,now).find(x=>x.id==="internal-series");assert.equal(issue?.step,5);assert.deepEqual(beginCorrection(issue!.step),{step:5,returnToReview:true})});
test("correction returns to review in one action",()=>assert.deepEqual(returnToReview(),{step:REVIEW_STEP,returnToReview:false}));
test("personal checklist shows only applicable items",()=>{const base={...EMPTY_DRAFT,birthDate:"1990-01-01",gender:"female",passportKind:"10y"} as Draft;const plain=buildPersonalKit({...base,changedName:"no",hasForeignPassport:"no"},now);assert.equal(plain.documents.some(x=>x.id==="foreign-passport"),false);assert.equal(plain.documents.some(x=>x.id==="name-docs"),false);const custom=buildPersonalKit({...base,changedName:"yes",hasForeignPassport:"yes"},now);assert.equal(custom.documents.some(x=>x.id==="foreign-passport"),true);assert.equal(custom.documents.some(x=>x.id==="name-docs"),true)});
test("analytics and feedback payloads contain no questionnaire fields",()=>{const metric=buildMetricPayload("kit_completed");const feedback=buildFeedbackPayload("up","  Понятно  ");assert.deepEqual(Object.keys(metric),["event"]);assert.deepEqual(Object.keys(feedback),["rating","message"]);assert.equal(JSON.stringify({metric,feedback}).includes("passport"),false)});
test("official Gosuslugi link is secure and has no PII query",()=>{const url=new URL(GOSUSLUGI_SERVICE_URL);assert.equal(url.protocol,"https:");assert.equal(url.hostname,"www.gosuslugi.ru");assert.equal(url.pathname,"/600101/1/form");assert.equal(url.search,"")});
test("CURRENT forms follow passport choice",()=>{assert.equal(getCurrentForm("5y").id,"passport-5y-186");assert.equal(getCurrentForm("10y").id,"passport-10y-996")});
test("FUTURE_DISABLED form cannot be selected",()=>assert.equal(canSelectForm("passport-future-83"),false));
