"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,ArrowRight,Check,Clipboard,Clock3,FileText,LockKeyhole,Plus,ShieldCheck,Trash2} from "lucide-react";
import {Button} from "@/components/ui/button"; import {Input} from "@/components/ui/input"; import {Label} from "@/components/ui/label"; import {Progress} from "@/components/ui/progress"; import {Textarea} from "@/components/ui/textarea"; import {Checkbox} from "@/components/ui/checkbox"; import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger} from "@/components/ui/alert-dialog";
import {EMPTY_DRAFT,type Activity,type Draft} from "@/lib/domain"; import {getCurrentForm} from "@/lib/forms"; import {analyzeTimeline,monthLabel,tenYearWindow} from "@/lib/timeline"; import {finishApplication,loadDraft,saveDraft} from "@/lib/storage"; import {validateDraft} from "@/lib/validation";

const STEPS=["Тип паспорта","Личные данные","Изменения ФИО","Адрес","Контакты","Паспорт РФ","Причина","Загранпаспорта","Важные обстоятельства","Деятельность","Проверка"];
const inputClass="h-12 rounded-xl border-slate-300 bg-white text-base";
const testBase={lastName:"ИВАНОВ",firstName:"ИВАН",middleName:"ИВАНОВИЧ",gender:"male",birthDate:"1988-05-12",birthPlace:"ГОР. ТОЛЬЯТТИ КУЙБЫШЕВСКОЙ ОБЛ.",changedName:"no",registeredAddress:"РОССИЯ, САМАРСКАЯ ОБЛ., Г. ТОЛЬЯТТИ, УЛ. ТЕСТОВАЯ, Д. 10, КВ. 15",registrationDate:"2014-06-10",livesAtRegistration:"yes",phone:"+7 900 000-00-00",email:"test@example.test",internalSeries:"0000",internalNumber:"000000",internalIssueDate:"2018-06-20",internalIssuer:"ТЕСТОВЫЙ ОРГАН МВД",reason:"first",hasForeignPassport:"no",restriction:"no",secretAccess:"no",contractualRestriction:"no"} as Partial<Draft>;
const fakeActivity=():Activity=>{const w=tenYearWindow();return{id:crypto.randomUUID(),kind:"work",from:w.start,to:"",current:true,organization:"ООО «ТЕСТ»",position:"СПЕЦИАЛИСТ",address:"Г. ТОЛЬЯТТИ, УЛ. УЧЕБНАЯ, Д. 1"}};

export default function Home(){
 const[step,setStep]=useState(-1),[draft,setDraft]=useState<Draft>(EMPTY_DRAFT),[ready,setReady]=useState(false),[notice,setNotice]=useState(""),[errors,setErrors]=useState<string[]>([]),[result,setResult]=useState(false);
 useEffect(()=>{const x=loadDraft(localStorage);if(x.data){setDraft(x.data);setNotice("Черновик восстановлен с этого устройства.")}if(x.expired)setNotice("Просроченный черновик автоматически удалён до открытия анкеты.");setReady(true)},[]);
 useEffect(()=>{if(!ready||!draft.consent||result)return;const t=setTimeout(()=>saveDraft(localStorage,draft),250);return()=>clearTimeout(t)},[draft,ready,result]);
 const update=<K extends keyof Draft>(k:K,v:Draft[K])=>setDraft(d=>({...d,[k]:v})); const timeline=useMemo(()=>analyzeTimeline(draft.activities),[draft.activities]);
 const fillTest=(kind:"5y"|"10y")=>{setDraft({...EMPTY_DRAFT,...testBase,consent:true,passportKind:kind,activities:[fakeActivity()]} as Draft);setStep(0);setNotice("Загружены только фиктивные тестовые данные.")};
 const erase=(done=false)=>{finishApplication(localStorage);setDraft(EMPTY_DRAFT);setStep(-1);setResult(false);setErrors([]);setNotice(done?"Оформление завершено. Локальные данные анкеты удалены с этого устройства. Скачанные вами файлы остаются только на вашем устройстве.":"Черновик удалён с этого устройства.")};
 const check=()=>{const x=validateDraft(draft);setErrors(x);if(!x.length)setResult(true)};
 if(!ready)return null; if(result&&draft.passportKind)return <Result draft={draft} onFinish={()=>erase(true)}/>;
 return <main className="min-h-screen bg-[#f3f8fb] text-slate-950"><Header hasDraft={draft.consent} onDelete={()=>erase()} onHome={()=>setStep(-1)}/>{notice&&<div className="mx-auto mt-5 max-w-3xl px-5"><div className="rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm">{notice}</div></div>}
 {step<0?<Landing draft={draft} update={update} start={()=>setStep(0)} fillTest={fillTest}/>:<div className="mx-auto grid max-w-6xl gap-8 px-5 py-8 lg:grid-cols-[240px_1fr]"><aside className="hidden lg:block"><div className="sticky top-8 rounded-3xl bg-sky-950 p-6 text-white"><p className="text-sky-200">Ваш прогресс</p><p className="text-2xl font-black">Шаг {step+1} из {STEPS.length}</p><Progress value={(step+1)/STEPS.length*100} className="mt-4 bg-white/20"/><ol className="mt-6 space-y-3 text-sm">{STEPS.map((s,i)=><li key={s} className={i===step?"font-bold":i<step?"text-sky-200":"text-slate-400"}>{i<step?"✓":"·"} {s}</li>)}</ol></div></aside><section><div className="mb-5 lg:hidden"><div className="mb-2 flex justify-between font-semibold"><span>Шаг {step+1} из {STEPS.length}</span><span>{Math.round((step+1)/STEPS.length*100)}%</span></div><Progress value={(step+1)/STEPS.length*100}/></div><div className="rounded-[2rem] border bg-white p-5 shadow-xl sm:p-9"><Step step={step} d={draft} update={update} timeline={timeline}/>{errors.length>0&&<div className="mt-7 rounded-2xl border border-red-200 bg-red-50 p-5"><b className="text-red-900">Нужно исправить</b><ul className="mt-3 space-y-2 text-red-950">{errors.map(e=><li key={e}>• {e}</li>)}</ul></div>}<div className="mt-8 flex flex-col-reverse justify-between gap-3 border-t pt-6 sm:flex-row"><Button variant="outline" size="lg" onClick={()=>setStep(s=>Math.max(-1,s-1))}><ArrowLeft/>Назад</Button>{step<STEPS.length-1?<Button size="lg" className="bg-sky-900" onClick={()=>{setErrors([]);setStep(s=>s+1)}}>Дальше<ArrowRight/></Button>:<Button size="lg" className="bg-emerald-700 text-lg" onClick={check}><Check/>Проверить анкету</Button>}</div></div><p className="mt-4 flex justify-center gap-2 text-sm text-slate-500"><Clock3 size={16}/>Черновик удалится через 24 часа после последней активности</p></section></div>}
 <footer className="border-t bg-white px-5 py-8 text-center text-sm leading-6 text-slate-600">Сервис помогает подготовить сведения и не является государственным органом, сайтом МВД или Госуслуг. Решение о выдаче загранпаспорта принимает уполномоченный государственный орган.</footer></main>;
}

type Update=<K extends keyof Draft>(k:K,v:Draft[K])=>void;
function Header({hasDraft,onDelete,onHome}:{hasDraft:boolean;onDelete:()=>void;onHome:()=>void}){return <header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><button onClick={onHome} className="flex items-center gap-3 text-left"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-sky-900 text-xl font-black text-white">З</span><span><b className="block text-lg">Загран без головняка</b><small className="text-slate-500">подготовка заявления 18+</small></span></button>{hasDraft&&<Confirm trigger={<Button variant="ghost"><Trash2/><span className="hidden sm:inline">Удалить черновик</span></Button>} title="Удалить черновик?" text="Все введённые данные будут удалены из браузера на этом устройстве." action="Удалить" onAction={onDelete}/>}</div></header>}
function Landing({draft,update,start,fillTest}:{draft:Draft;update:Update;start:()=>void;fillTest:(k:"5y"|"10y")=>void}){return <section className="mx-auto max-w-6xl px-5 py-12 sm:py-16"><div className="grid items-center gap-10 lg:grid-cols-[1.15fr_.85fr]"><div><span className="inline-flex items-center gap-2 rounded-full bg-sky-100 px-4 py-2 text-sm font-bold"><ShieldCheck size={17}/>Данные остаются на вашем устройстве</span><h1 className="mt-5 max-w-3xl text-4xl font-black leading-[1.05] tracking-[-.04em] sm:text-6xl">Загранпаспорт без головной боли</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl">Ответьте на простые вопросы. Сервис проверит данные, найдёт пропуски за последние 10 лет и подготовит всё для переноса в заявление.</p><div className="mt-8 rounded-2xl border border-sky-200 bg-white p-5"><div className="flex gap-4"><LockKeyhole className="shrink-0 text-sky-800"/><div><b>Сначала — о приватности</b><p className="mt-2 leading-7 text-slate-600">Ваши паспортные и персональные данные используются только на вашем устройстве для подготовки заявления. Мы не сохраняем содержимое анкеты на нашем сервере. После завершения оформления локальный черновик автоматически удаляется.</p><label className="mt-4 flex cursor-pointer gap-3 font-semibold"><Checkbox checked={draft.consent} onCheckedChange={v=>update("consent",v===true)}/>Я понимаю и хочу продолжить</label></div></div></div><Button disabled={!draft.consent} onClick={start} size="lg" className="mt-6 h-14 bg-sky-900 px-8 text-lg">Начать оформление<ArrowRight/></Button></div><div className="rounded-[2rem] bg-sky-950 p-8 text-white"><p className="font-black uppercase tracking-widest text-cyan-300">Что важно</p><ul className="mt-6 space-y-5 text-lg"><li>✓ Без пароля и SMS-кода Госуслуг</li><li>✓ Паспорта на 5 и 10 лет</li><li>✓ Проверка пропусков и пересечений</li><li>✓ Никакой отправки анкеты в интернет</li></ul><div className="mt-8 border-t border-white/15 pt-6"><p className="text-sm text-sky-200">Режим владельца · фиктивные данные</p><div className="mt-3 flex gap-2"><Button variant="secondary" onClick={()=>fillTest("5y")}>Тест 5 лет</Button><Button variant="secondary" onClick={()=>fillTest("10y")}>Тест 10 лет</Button></div></div></div></div></section>}

function Step({step,d,update,timeline}:{step:number;d:Draft;update:Update;timeline:ReturnType<typeof analyzeTimeline>}){
 const yn=(k:keyof Draft)=><RadioGroup value={String(d[k])} onValueChange={v=>update(k,v as never)} className="grid grid-cols-2 gap-3"><Choice value="no" label="Нет"/><Choice value="yes" label="Да"/></RadioGroup>;
 if(step===0)return <><Title over="Выберите вариант" title="Какой паспорт вы хотите оформить?" text="От этого зависит официальная форма проверки."/><div className="grid gap-4 sm:grid-cols-2"><Passport active={d.passportKind==="10y"} onClick={()=>update("passportKind","10y")} years="10 лет" text="Биометрический, с электронным носителем" order="Форма №996"/><Passport active={d.passportKind==="5y"} onClick={()=>update("passportKind","5y")} years="5 лет" text="Без электронного носителя" order="Форма №186"/></div>{d.passportKind==="5y"&&<Info>Внесение сведений о детях до 14 лет пока не поддерживается MVP.</Info>}</>;
 if(step===1)return <><Title over="О вас" title="Основные личные данные" text="Перепишите сведения точно по внутреннему паспорту."/><div className="grid gap-5 sm:grid-cols-2"><Field label="Фамилия" value={d.lastName} set={v=>update("lastName",v)}/><Field label="Имя" value={d.firstName} set={v=>update("firstName",v)}/><Field label="Отчество" value={d.middleName} disabled={d.noMiddleName} set={v=>update("middleName",v)}/><label className="flex items-center gap-3 pt-8"><Checkbox checked={d.noMiddleName} onCheckedChange={v=>update("noMiddleName",v===true)}/>Отчества нет</label><div><Label className="mb-2 block">Пол</Label><RadioGroup value={d.gender} onValueChange={v=>update("gender",v as Draft["gender"])} className="grid grid-cols-2 gap-3"><Choice value="male" label="Мужской"/><Choice value="female" label="Женский"/></RadioGroup></div><Field label="Дата рождения" type="date" value={d.birthDate} set={v=>update("birthDate",v)}/><div className="sm:col-span-2"><Field label="Место рождения" value={d.birthPlace} set={v=>update("birthPlace",v)} hint="Точно как в паспорте, включая сокращения."/></div></div></>;
 if(step===2)return <><Title over="История ФИО" title="Вы когда-нибудь меняли фамилию, имя или отчество?" text="Официальная форма требует дату и место изменения."/>{yn("changedName")}{d.changedName==="yes"&&<div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Прежние ФИО" value={d.previousName} set={v=>update("previousName",v)}/><Field label="Дата изменения" type="date" value={d.changeDate} set={v=>update("changeDate",v)}/><div className="sm:col-span-2"><Field label="Место изменения" value={d.changePlace} set={v=>update("changePlace",v)}/></div><Info>В MVP поддерживается одна запись. Несколько изменений требуют ручной сверки с приложением к форме.</Info></div>}</>;
 if(step===3)return <><Title over="Адрес" title="Где вы зарегистрированы и живёте?" text="Укажите адрес полностью, как в документах."/><div className="space-y-5"><Field label="Адрес постоянной регистрации" value={d.registeredAddress} set={v=>update("registeredAddress",v)}/><Field label="Дата регистрации" type="date" value={d.registrationDate} set={v=>update("registrationDate",v)}/><div><Label className="mb-3 block text-base">Живёте по адресу регистрации?</Label>{yn("livesAtRegistration")}</div>{d.livesAtRegistration==="no"&&<Field label="Адрес места пребывания или фактического проживания" value={d.actualAddress} set={v=>update("actualAddress",v)}/>}</div></>;
 if(step===4)return <><Title over="Связь" title="Как с вами связаться?" text="Оба поля отмечены в формах как необязательные."/><div className="grid gap-5 sm:grid-cols-2"><Field label="Телефон (по желанию)" value={d.phone} set={v=>update("phone",v)}/><Field label="E-mail (по желанию)" type="email" value={d.email} set={v=>update("email",v)}/></div></>;
 if(step===5)return <><Title over="Подготовьте документ" title="Возьмите российский паспорт" text="Сейчас понадобятся данные из него."/><div className="grid gap-5 sm:grid-cols-2"><Field label="Серия — 4 цифры" value={d.internalSeries} maxLength={4} set={v=>update("internalSeries",v.replace(/\D/g,""))}/><Field label="Номер — 6 цифр" value={d.internalNumber} maxLength={6} set={v=>update("internalNumber",v.replace(/\D/g,""))}/><Field label="Дата выдачи" type="date" value={d.internalIssueDate} set={v=>update("internalIssueDate",v)}/><div className="sm:col-span-2"><Field label="Кем выдан" value={d.internalIssuer} set={v=>update("internalIssuer",v)}/></div></div></>;
 if(step===6)return <><Title over="Основание" title="Почему вы оформляете паспорт?" text="Выберите один вариант в официальном смысле формы."/><RadioGroup value={d.reason} onValueChange={v=>update("reason",v as Draft["reason"])} className="grid gap-3">{[["first","Первичное получение"],["additional","В дополнение к действующему"],["replace","Взамен действующего"],["lost","Взамен утраченного"],["damaged","Взамен использованного или испорченного"]].map(([v,l])=><Choice key={v} value={v} label={l}/>)}</RadioGroup></>;
 if(step===7)return <><Title over="Другие документы" title="Есть ли действующий загранпаспорт?" text="Укажите сведения, необходимые официальной форме."/>{yn("hasForeignPassport")}{d.hasForeignPassport==="yes"&&<div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Серия" value={d.foreignSeries} set={v=>update("foreignSeries",v)}/><Field label="Номер" value={d.foreignNumber} set={v=>update("foreignNumber",v)}/><Field label="Дата выдачи" type="date" value={d.foreignIssueDate} set={v=>update("foreignIssueDate",v)}/><Field label="Кем выдан" value={d.foreignIssuer} set={v=>update("foreignIssuer",v)}/><label className="flex gap-3"><Checkbox checked={d.foreignForCancellation} onCheckedChange={v=>update("foreignForCancellation",v===true)}/>Будет представлен для аннулирования</label><label className="flex gap-3"><Checkbox checked={d.foreignLost} onCheckedChange={v=>update("foreignLost",v===true)}/>Утрачен</label><Info>В MVP поддерживается один паспорт. Несколько паспортов требуют ручной сверки.</Info></div>}</>;
 if(step===8)return <><Title over="Официальные вопросы" title="Важные обстоятельства" text="Ответ «Да» не означает автоматического отказа. Сервис не определяет право на выезд."/><Legal title="Есть ли обстоятельства, при которых может быть ограничено ваше право на выезд из РФ?" control={yn("restriction")} open={d.restriction==="yes"} value={d.restrictionDetails} set={v=>update("restrictionDetails",v)}/><Legal title="Был ли допуск к сведениям особой важности или совершенно секретным сведениям?" control={yn("secretAccess")} open={d.secretAccess==="yes"} value={d.secretDetails} set={v=>update("secretDetails",v)}/><Legal title="Есть ли договорные обязательства, препятствующие выезду?" control={yn("contractualRestriction")} open={d.contractualRestriction==="yes"} value={d.contractDetails} set={v=>update("contractDetails",v)}/><Info>Ваш случай может требовать дополнительной проверки. Сервис сохраняет сведения для анкеты, но не делает юридических выводов.</Info></>;
 if(step===9)return <Timeline d={d} update={update} analysis={timeline}/>;
 return <><Title over="Финальная проверка" title="Проверьте анкету" text="Проверим обязательные поля, даты, реквизиты и десятилетний период."/><div className="grid gap-4 sm:grid-cols-3"><Summary icon={<FileText/>} title={d.passportKind?getCurrentForm(d.passportKind).title:"Тип не выбран"} text={d.passportKind?getCurrentForm(d.passportKind).order:"Вернитесь к шагу 1"}/><Summary icon={<ShieldCheck/>} title="Локально" text="Анкета не уходит на сервер"/><Summary icon={<Clock3/>} title="24 часа" text="После этого черновик удалится"/></div><div className="mt-7 rounded-2xl bg-slate-100 p-5"><b>Перед подачей сверьте сведения с оригиналами документов.</b><p className="mt-2 text-slate-600">Результат — лист подготовленных данных, а не поддельный официальный бланк.</p></div></>;
}

function Timeline({d,update,analysis}:{d:Draft;update:Update;analysis:ReturnType<typeof analyzeTimeline>}){const patch=(id:string,p:Partial<Activity>)=>update("activities",d.activities.map(a=>a.id===id?{...a,...p}:a));const add=()=>update("activities",[...d.activities,{id:crypto.randomUUID(),kind:"work",from:"",to:"",current:false,organization:"",position:"",address:""}]);return <><Title over="Последние 10 лет" title="Чем вы занимались в каждый месяц?" text={`Покройте период с ${monthLabel(analysis.window.start)} по ${monthLabel(analysis.window.end)} без пропусков и пересечений.`}/><div className="space-y-4">{d.activities.map((a,i)=><div key={a.id} className="rounded-2xl border bg-slate-50 p-5"><div className="mb-4 flex justify-between"><b>Период {i+1}</b><Button variant="ghost" size="icon" onClick={()=>update("activities",d.activities.filter(x=>x.id!==a.id))}><Trash2/></Button></div><div className="grid gap-4 sm:grid-cols-2"><div><Label className="mb-2 block">Вид деятельности</Label><select className={`${inputClass} w-full px-3`} value={a.kind} onChange={e=>patch(a.id,{kind:e.target.value as Activity["kind"]})}><option value="work">Работа</option><option value="study">Учёба</option><option value="service">Военная служба</option><option value="unemployed">Не работал(а)</option></select></div><Field label="С месяца" type="month" value={a.from} set={v=>patch(a.id,{from:v})}/><Field label="По месяц" type="month" value={a.to} disabled={a.current} set={v=>patch(a.id,{to:v})}/><label className="flex items-center gap-3 pt-8"><Checkbox checked={a.current} onCheckedChange={v=>patch(a.id,{current:v===true,to:v?"":a.to})}/>По настоящее время</label><Field label="Организация / учебное заведение / НЕ РАБОТАЛ(А)" value={a.organization} set={v=>patch(a.id,{organization:v})}/><Field label="Должность" value={a.position} set={v=>patch(a.id,{position:v})}/><div className="sm:col-span-2"><Field label="Адрес" value={a.address} set={v=>patch(a.id,{address:v})}/></div></div></div>)}<Button variant="outline" className="h-12 w-full border-dashed" onClick={add}><Plus/>Добавить период</Button></div><div className={`mt-6 rounded-2xl p-5 ${analysis.complete?"bg-emerald-50":"bg-amber-50"}`}><b>{analysis.complete?"Весь период заполнен без пересечений":"Проверка периода"}</b>{analysis.gaps.map(g=><p key={g.from}>Не заполнено: {monthLabel(g.from)} — {monthLabel(g.to)}</p>)}{analysis.overlaps.map(g=><p key={g.from}>Пересечение: {monthLabel(g.from)} — {monthLabel(g.to)}</p>)}</div></>}

function Result({draft:d,onFinish}:{draft:Draft;onFinish:()=>void}){const form=getCurrentForm(d.passportKind as "5y"|"10y");const rows=[["ФИО",`${d.lastName} ${d.firstName} ${d.noMiddleName?"":d.middleName}`.trim()],["Рождение",`${d.birthDate} · ${d.birthPlace}`],["Адрес",`${d.registeredAddress} · с ${d.registrationDate}`],["Паспорт РФ",`${d.internalSeries} ${d.internalNumber}, ${d.internalIssueDate}, ${d.internalIssuer}`],["Причина",({first:"Первичное",additional:"В дополнение",replace:"Взамен действующего",lost:"Взамен утраченного",damaged:"Взамен испорченного","":"Не указано"})[d.reason]]];return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><div className="no-print mx-auto mb-5 flex max-w-4xl flex-wrap justify-between gap-3"><div><p className="font-bold text-emerald-700">Проверка пройдена</p><h1 className="text-2xl font-black">Подготовленные данные</h1></div><div className="flex gap-2"><Button variant="outline" onClick={()=>window.print()}><FileText/>Сохранить как PDF</Button><Confirm trigger={<Button className="bg-red-700"><Trash2/>Завершить оформление</Button>} title="Завершить и удалить данные?" text="Черновик и чувствительное состояние будут удалены. Сохранённые вами файлы останутся." action="Завершить и удалить" onAction={onFinish}/></div></div><article className="print-sheet mx-auto max-w-4xl bg-white p-7 shadow-xl sm:p-12"><p className="font-black uppercase tracking-widest text-sky-800">Лист подготовленных данных · не официальный бланк</p><h2 className="mt-2 text-3xl font-black">Заявление на загранпаспорт</h2><p>{form.title} · {form.order} · CURRENT</p><p className="mt-6 rounded-xl bg-amber-50 p-4 text-sm"><b>Важно:</b> это лист для сверки и переноса, а не воспроизведение официальной формы МВД. Экраны Госуслуг могут отличаться.</p><div className="mt-7 divide-y border-y">{rows.map(([l,v])=><div key={l} className="grid gap-1 py-4 sm:grid-cols-[170px_1fr]"><b className="text-slate-600">{l}</b><span>{v}</span></div>)}</div><h3 className="mt-9 text-xl font-black">Деятельность за 10 лет</h3>{d.activities.map(a=><div key={a.id} className="mt-3 rounded-xl border p-4"><b>{a.from} — {a.current?"настоящее время":a.to}</b><p>{a.organization} · {a.position}</p><p className="text-slate-600">{a.address}</p></div>)}<h3 className="mt-9 text-xl font-black">Перенос в Госуслуги</h3><p className="text-slate-600">Копируйте значения по одному и сверяйте название поля на текущем экране.</p><div className="no-print mt-4 grid gap-3 sm:grid-cols-2">{rows.map(([l,v])=><button key={l} onClick={()=>navigator.clipboard.writeText(v)} className="flex justify-between rounded-xl border p-4 text-left"><span><small className="block text-slate-500">{l}</small><b>{v}</b></span><Clipboard/></button>)}</div><p className="mt-10 border-t pt-5 text-sm text-slate-600">Перед подачей сверьте сведения с оригиналами. Сервис не гарантирует выдачу и не определяет право на выезд.</p></article></main>}

function Title({over,title,text}:{over:string;title:string;text:string}){return <div className="mb-7"><p className="font-black uppercase tracking-widest text-sky-800">{over}</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{title}</h2><p className="mt-3 text-lg leading-7 text-slate-600">{text}</p></div>}
function Field({label,hint,set,...p}:React.ComponentProps<typeof Input>&{label:string;hint?:string;set:(v:string)=>void}){return <div><Label className="mb-2 block text-base">{label}</Label><Input {...p} onChange={e=>set(e.target.value)} className={inputClass}/>{hint&&<p className="mt-2 text-sm text-slate-500">{hint}</p>}</div>}
function Choice({value,label}:{value:string;label:string}){return <label className="flex min-h-14 cursor-pointer items-center gap-3 rounded-xl border p-4 font-semibold has-[[data-checked]]:border-sky-700 has-[[data-checked]]:bg-sky-50"><RadioGroupItem value={value}/>{label}</label>}
function Passport({active,onClick,years,text,order}:{active:boolean;onClick:()=>void;years:string;text:string;order:string}){return <button onClick={onClick} className={`rounded-2xl border-2 p-6 text-left ${active?"border-sky-700 bg-sky-50 shadow-lg":"border-slate-200"}`}><b className="text-3xl">На {years}</b><span className="mt-3 block text-slate-600">{text}</span><span className="mt-5 inline-block rounded-full bg-slate-900 px-3 py-1 text-sm font-bold text-white">{order}</span></button>}
function Info({children}:{children:React.ReactNode}){return <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6">{children}</div>}
function Legal({title,control,open,value,set}:{title:string;control:React.ReactNode;open:boolean;value:string;set:(v:string)=>void}){return <div className="mb-5 rounded-2xl border p-5"><h3 className="mb-4 text-lg font-bold">{title}</h3>{control}{open&&<Textarea className="mt-4 min-h-24 text-base" value={value} onChange={e=>set(e.target.value)} placeholder="Укажите организацию, год или обстоятельства"/>}</div>}
function Summary({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-2xl border bg-slate-50 p-5"><span className="text-sky-800">{icon}</span><b className="mt-3 block">{title}</b><p className="mt-1 text-sm text-slate-600">{text}</p></div>}
function Confirm({trigger,title,text,action,onAction}:{trigger:React.ReactNode;title:string;text:string;action:string;onAction:()=>void}){return <AlertDialog><AlertDialogTrigger asChild>{trigger}</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{text}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Отмена</AlertDialogCancel><AlertDialogAction onClick={onAction} className="bg-red-700">{action}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
