import type { Draft } from "./domain"; import {analyzeTimeline,monthLabel} from "./timeline";
export function validateDraft(d:Draft,now=new Date()){
 const e:string[]=[]; const req:[unknown,string][]=[[d.passportKind,"Выберите срок действия паспорта."],[d.lastName,"Укажите фамилию."],[d.firstName,"Укажите имя."],[d.gender,"Укажите пол."],[d.birthDate,"Укажите дату рождения."],[d.birthPlace,"Укажите место рождения."],[d.changedName,"Ответьте на вопрос об изменении ФИО."],[d.registeredAddress,"Укажите адрес постоянной регистрации."],[d.registrationDate,"Укажите дату регистрации."],[d.livesAtRegistration,"Укажите, живёте ли вы по адресу регистрации."],[d.internalIssueDate,"Укажите дату выдачи внутреннего паспорта."],[d.internalIssuer,"Укажите, кем выдан внутренний паспорт."],[d.reason,"Выберите причину оформления."],[d.hasForeignPassport,"Ответьте на вопрос о действующих загранпаспортах."],[d.restriction,"Ответьте на вопрос об ограничениях права на выезд."],[d.secretAccess,"Ответьте на вопрос о допуске к гостайне."],[d.contractualRestriction,"Ответьте на вопрос о договорных обязательствах."]]; req.forEach(([v,m])=>{if(!v)e.push(m)});
 if(!d.noMiddleName&&!d.middleName.trim())e.push("Укажите отчество или отметьте, что его нет."); if(!/^\d{4}$/.test(d.internalSeries))e.push("Серия внутреннего паспорта должна состоять из 4 цифр."); if(!/^\d{6}$/.test(d.internalNumber))e.push("Номер внутреннего паспорта должен состоять из 6 цифр.");
 if(d.livesAtRegistration==="no"&&!d.actualAddress.trim())e.push("Укажите адрес места пребывания или фактического проживания."); if(d.changedName==="yes"&&(!d.previousName||!d.changeDate||!d.changePlace))e.push("Заполните прежние ФИО, дату и место изменения."); if(d.hasForeignPassport==="yes"&&(!d.foreignSeries||!d.foreignNumber||!d.foreignIssueDate||!d.foreignIssuer))e.push("Заполните сведения о действующем загранпаспорте.");
 if(d.restriction==="yes"&&!d.restrictionDetails)e.push("Опишите обстоятельства возможного ограничения права на выезд."); if(d.secretAccess==="yes"&&!d.secretDetails)e.push("Укажите организацию и год допуска."); if(d.contractualRestriction==="yes"&&!d.contractDetails)e.push("Укажите организацию и год обязательства.");
 for(const date of [d.birthDate,d.registrationDate,d.internalIssueDate,d.foreignIssueDate].filter(Boolean))if(new Date(date)>now)e.push("Дата не может быть в будущем.");
 const t=analyzeTimeline(d.activities,now);t.invalid.forEach(()=>e.push("В одном из периодов некорректны даты."));t.gaps.forEach(g=>e.push(`Не заполнен период: ${monthLabel(g.from)} — ${monthLabel(g.to)}.`));t.overlaps.forEach(g=>e.push(`Периоды пересекаются: ${monthLabel(g.from)} — ${monthLabel(g.to)}.`));return [...new Set(e)];
}
