CREATE TABLE IF NOT EXISTS daily_metrics (
  day TEXT PRIMARY KEY,
  visits INTEGER NOT NULL DEFAULT 0,
  starts INTEGER NOT NULL DEFAULT 0,
  reviews INTEGER NOT NULL DEFAULT 0,
  kits INTEGER NOT NULL DEFAULT 0,
  gosuslugi_clicks INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS feedback (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rating TEXT CHECK (rating IN ('up', 'down') OR rating IS NULL),
  message TEXT NOT NULL DEFAULT ''
);
